//first.js
const menu = [
    { name: "ADZUKI BEANS", category: "Vegetable", color: "green" },
  { name: "ALLSPICE", category: "Herb/Spice", color: "green" },
  { name: "ALLULOSE", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "ARUGULA", category: "Vegetable", color: "green" },
  { name: "BAKER'S YEAST", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "BLACK CURRANT", category: "Fruit", color: "green" },
  { name: "BUTTON MUSHROOM", category: "Vegetable", color: "green" },
  { name: "CANTALOUPE", category: "Fruit", color: "green" },
  { name: "CARAWAY", category: "Herb/Spice", color: "green" },
  { name: "CHIA", category: "Vegetable", color: "green" },
  { name: "CHICORY", category: "Vegetable", color: "green" },
  { name: "CRAB", category: "Seafood", color: "green" },
  { name: "CRANBERRY", category: "Fruit", color: "green" },
  { name: "CUMIN", category: "Herb/Spice", color: "green" },
  { name: "DATE", category: "Fruit", color: "green" },
  { name: "LIME", category: "Fruit", color: "green" },
  { name: "MACKEREL", category: "Vegetable", color: "green" },
  { name: "MONK FRUIT", category: "Fruit", color: "green" },
  { name: "MUSSEL", category: "Seafood", color: "green" },
  { name: "NECTARINE", category: "Fruit", color: "green" },
  { name: "NUTRITIONAL YEAST", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "PINTO BEAN", category: "Vegetable", color: "green" },
  { name: "PUMPKIN", category: "Vegetable", color: "green" },
  { name: "RADISH", category: "Vegetable", color: "green" },
  { name: "RASPBERRY", category: "Fruit", color: "green" },
  { name: "SCALLION", category: "Vegetable", color: "green" },
  { name: "SEA BASS", category: "Seafood", color: "green" },
  { name: "SHRIMP", category: "Seafood", color: "green" },
  { name: "ZUCCHINI SQUASH", category: "Vegetable", color: "green" },
  { name: "AMARANTH", category: "Vegetable", color: "green" },
  { name: "ANCHOVY", category: "Seafood", color: "green" },
  { name: "APPLE", category: "Fruit", color: "green" },
  { name: "APRICOT", category: "Fruit", color: "green" },
  { name: "ARROWROOT", category: "Vegetable", color: "green" },
  { name: "ASPARAGUS", category: "Vegetable", color: "green" },
  { name: "BANANA", category: "Fruit", color: "green" },
  { name: "BELL PEPPER MIX", category: "Vegetable", color: "green" },
  { name: "BLACK TEA", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "BOSTON BIBB LETTUCE", category: "Vegetable", color: "green" },
  { name: "BROCCOLI", category: "Vegetable", color: "green" },
  { name: "BRSSLS SPROUT", category: "Vegetable", color: "green" },
  { name: "BUCKWHEAT", category: "Vegetable", color: "green" },
  { name: "CAROB", category: "Vegetable", color: "green" },
  { name: "CARROT", category: "Vegetable", color: "green" },
  { name: "CAYENNE PEPPER", category: "Herb/Spice", color: "green" },
  { name: "CELERY", category: "Vegetable", color: "green" },
  { name: "CILANTRO", category: "Herb/Spice", color: "green" },
  { name: "CLOVE", category: "Herb/Spice", color: "green" },
  { name: "COFFEE", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "COLLARD GREENS", category: "Vegetable", color: "green" },
  { name: "CORIANDER SEED", category: "Herb/Spice", color: "green" },
  { name: "DANDELION LEAF", category: "Vegetable", color: "green" },
  { name: "DILL", category: "Herb/Spice", color: "green" },
  { name: "DRAGON FRUIT", category: "Fruit", color: "green" },
  { name: "DUCK", category: "Meat", color: "green" },
  { name: "ENDIVE", category: "Vegetable", color: "green" },
  { name: "GREEN PEA", category: "Vegetable", color: "green" },
  { name: "GROUPER", category: "Seafood", color: "green" },
  { name: "HABANERO PEPPER", category: "Vegetable", color: "green" },
  { name: "HADDOCK", category: "Seafood", color: "green" },
  { name: "HOPS", category: "Vegetable", color: "green" },
  { name: "ICEBERG LETTUCE", category: "Vegetable", color: "green" },
  { name: "KELP", category: "Vegetable", color: "green" },
  { name: "LAMB", category: "Meat", color: "green" },
  { name: "MAHI MAHI", category: "Seafood", color: "green" },
  { name: "MUNG BEAN", category: "Vegetable", color: "green" },
  { name: "NAVY BEAN", category: "Vegetable", color: "green" },
  { name: "NUTMEG", category: "Herb/Spice", color: "green" },
  { name: "OLIVE", category: "Vegetable", color: "green" },
  { name: "OYSTER", category: "Seafood", color: "green" },
  { name: "PAPAYA", category: "Fruit", color: "green" },
  { name: "PINEAPPLE", category: "Fruit", color: "green" },
  { name: "PLUM", category: "Fruit", color: "green" },
  { name: "POLLOCK", category: "Seafood", color: "green" },
  { name: "POMEGRANATE", category: "Fruit", color: "green" },
  { name: "PORK", category: "Meat", color: "green" },
  { name: "SAFFLOWER", category: "Vegetable", color: "green" },
  { name: "SAFFRON", category: "Herb/Spice", color: "green" },
  { name: "SAGE", category: "Herb/Spice", color: "green" },
  { name: "SARDINE", category: "Seafood", color: "green" },
  { name: "SHIITAKE MUSHRM", category: "Vegetable", color: "green" },
  { name: "SOLE", category: "Seafood", color: "green" },
  { name: "SORGHUM", category: "Vegetable", color: "green" },
  { name: "SOYBEAN", category: "Vegetable", color: "green" },
  { name: "SPAGHETTI SQUASH", category: "Vegetable", color: "green" },
  { name: "STRING BEAN", category: "Vegetable", color: "green" },
  { name: "SUNFLOWER", category: "Vegetable", color: "green" },
  { name: "SWISS CHARD", category: "Vegetable", color: "green" },
  { name: "TARRAGON", category: "Herb/Spice", color: "green" },
  { name: "TURMERIC", category: "Herb/Spice", color: "green" },
  { name: "WALNUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "WATER CHESTNUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "WATERCRESS", category: "Vegetable", color: "green" },
  { name: "WATERMELON", category: "Fruit", color: "green" },
  { name: "WILD RICE", category: "Grain/Starch", color: "green" },
  { name: "YELLOW PEA", category: "Vegetable", color: "green" },
  { name: "YELLOW SQUASH", category: "Vegetable", color: "green" },
]
module.exports = { menu };