//first.js
const menuStart = [
    { name: "ADZUKI BEANS", category: "Vegetable", color: "green" },
  { name: "ALLSPICE", category: "Herb/Spice", color: "green" },
  { name: "ALLULOSE", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "ARUGULA", category: "Vegetable", color: "green" },
  { name: "BAKER'S YEAST", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "BLACK CURRANT", category: "Fruit", color: "green" },
  { name: "BUTTON MUSHROOM", category: "Vegetable", color: "green" },
  { name: "CANTALOUPE", category: "Fruit", color: "green" },
  { name: "CARAWAY", category: "Herb/Spice", color: "green" },
  { name: "CHIA", category: "Vegetable", color: "green" },
  { name: "CHICORY", category: "Vegetable", color: "green" },
  { name: "CRAB", category: "Seafood", color: "green" },
  { name: "CRANBERRY", category: "Fruit", color: "green" },
  { name: "CUMIN", category: "Herb/Spice", color: "green" },
  { name: "DATE", category: "Fruit", color: "green" },
  { name: "LIME", category: "Fruit", color: "green" },
  { name: "MACKEREL", category: "Vegetable", color: "green" },
  { name: "MONK FRUIT", category: "Fruit", color: "green" },
  { name: "MUSSEL", category: "Seafood", color: "green" },
  { name: "NECTARINE", category: "Fruit", color: "green" },
  { name: "NUTRITIONAL YEAST", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "PINTO BEAN", category: "Vegetable", color: "green" },
  { name: "PUMPKIN", category: "Vegetable", color: "green" },
  { name: "RADISH", category: "Vegetable", color: "green" },
  { name: "RASPBERRY", category: "Fruit", color: "green" },
  { name: "SCALLION", category: "Vegetable", color: "green" },
  { name: "SEA BASS", category: "Seafood", color: "green" },
  { name: "SHRIMP", category: "Seafood", color: "green" },
  { name: "ZUCCHINI SQUASH", category: "Vegetable", color: "green" },
  { name: "AMARANTH", category: "Vegetable", color: "green" },
  { name: "ANCHOVY", category: "Seafood", color: "green" },
  { name: "APPLE", category: "Fruit", color: "green" },
  { name: "APRICOT", category: "Fruit", color: "green" },
  { name: "ARROWROOT", category: "Vegetable", color: "green" },
  { name: "ASPARAGUS", category: "Vegetable", color: "green" },
  { name: "BANANA", category: "Fruit", color: "green" },
  { name: "BELL PEPPER MIX", category: "Vegetable", color: "green" },
  { name: "BLACK TEA", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "BOSTON BIBB LETTUCE", category: "Vegetable", color: "green" },
  { name: "BROCCOLI", category: "Vegetable", color: "green" },
  { name: "BRSSLS SPROUT", category: "Vegetable", color: "green" },
  { name: "BUCKWHEAT", category: "Vegetable", color: "green" },
  { name: "CAROB", category: "Vegetable", color: "green" },
  { name: "CARROT", category: "Vegetable", color: "green" },
  { name: "CAYENNE PEPPER", category: "Herb/Spice", color: "green" },
  { name: "CELERY", category: "Vegetable", color: "green" },
  { name: "CILANTRO", category: "Herb/Spice", color: "green" },
  { name: "CLOVE", category: "Herb/Spice", color: "green" },
  { name: "COFFEE", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "COLLARD GREENS", category: "Vegetable", color: "green" },
  { name: "CORIANDER SEED", category: "Herb/Spice", color: "green" },
  { name: "DANDELION LEAF", category: "Vegetable", color: "green" },
  { name: "DILL", category: "Herb/Spice", color: "green" },
  { name: "DRAGON FRUIT", category: "Fruit", color: "green" },
  { name: "DUCK", category: "Meat", color: "green" },
  { name: "ENDIVE", category: "Vegetable", color: "green" },
  { name: "GREEN PEA", category: "Vegetable", color: "green" },
  { name: "GROUPER", category: "Seafood", color: "green" },
  { name: "HABANERO PEPPER", category: "Vegetable", color: "green" },
  { name: "HADDOCK", category: "Seafood", color: "green" },
  { name: "HOPS", category: "Vegetable", color: "green" },
  { name: "ICEBERG LETTUCE", category: "Vegetable", color: "green" },
  { name: "KELP", category: "Vegetable", color: "green" },
  { name: "LAMB", category: "Meat", color: "green" },
  { name: "MAHI MAHI", category: "Seafood", color: "green" },
  { name: "MUNG BEAN", category: "Vegetable", color: "green" },
  { name: "NAVY BEAN", category: "Vegetable", color: "green" },
  { name: "NUTMEG", category: "Herb/Spice", color: "green" },
  { name: "OLIVE", category: "Vegetable", color: "green" },
  { name: "OYSTER", category: "Seafood", color: "green" },
  { name: "PAPAYA", category: "Fruit", color: "green" },
  { name: "PINEAPPLE", category: "Fruit", color: "green" },
  { name: "PLUM", category: "Fruit", color: "green" },
  { name: "POLLOCK", category: "Seafood", color: "green" },
  { name: "POMEGRANATE", category: "Fruit", color: "green" },
  { name: "PORK", category: "Meat", color: "green" },
  { name: "SAFFLOWER", category: "Vegetable", color: "green" },
  { name: "SAFFRON", category: "Herb/Spice", color: "green" },
  { name: "SAGE", category: "Herb/Spice", color: "green" },
  { name: "SARDINE", category: "Seafood", color: "green" },
  { name: "SHIITAKE MUSHRM", category: "Vegetable", color: "green" },
  { name: "SOLE", category: "Seafood", color: "green" },
  { name: "SORGHUM", category: "Vegetable", color: "green" },
  { name: "SOYBEAN", category: "Vegetable", color: "green" },
  { name: "SPAGHETTI SQUASH", category: "Vegetable", color: "green" },
  { name: "STRING BEAN", category: "Vegetable", color: "green" },
  { name: "SUNFLOWER", category: "Vegetable", color: "green" },
  { name: "SWISS CHARD", category: "Vegetable", color: "green" },
  { name: "TARRAGON", category: "Herb/Spice", color: "green" },
  { name: "TURMERIC", category: "Herb/Spice", color: "green" },
  { name: "WALNUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "WATER CHESTNUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "WATERCRESS", category: "Vegetable", color: "green" },
  { name: "WATERMELON", category: "Fruit", color: "green" },
  { name: "WILD RICE", category: "Grain/Starch", color: "green" },
  { name: "YELLOW PEA", category: "Vegetable", color: "green" },
  { name: "YELLOW SQUASH", category: "Vegetable", color: "green" },
  { name: "ACORN SQUASH", category: "Vegetable", color: "green" },
  { name: "BOK CHOY", category: "Vegetable", color: "green" },
  { name: "CAULIFLOWER", category: "Vegetable", color: "green" },
  { name: "ESCAROLE", category: "Vegetable", color: "green" },
  { name: "JICAMA", category: "Vegetable", color: "green" },
  { name: "LEEK", category: "Vegetable", color: "green" },
  { name: "NORI", category: "Vegetable", color: "green" },
  { name: "PORTOBELLO MUSHROOM", category: "Vegetable", color: "green" },
  { name: "RUTABAGA", category: "Vegetable", color: "green" },
  { name: "TARO ROOT", category: "Vegetable", color: "green" },
  { name: "WHITE POTATO", category: "Vegetable", color: "green" },
  { name: "ARTICHOKE", category: "Vegetable", color: "green" },
  { name: "BUTTERNUT SQUASH", category: "Vegetable", color: "green" },
  { name: "CHICKPEA", category: "Vegetable", color: "green" },
  { name: "FAVA BEAN", category: "Vegetable", color: "green" },
  { name: "KALE", category: "Vegetable", color: "green" },
  { name: "LENTIL BEAN", category: "Vegetable", color: "green" },
  { name: "OKRA", category: "Vegetable", color: "green" },
  { name: "RED BEET", category: "Vegetable", color: "green" },
  { name: "SHALLOTS", category: "Vegetable", color: "green" },
  { name: "TOMATO", category: "Vegetable", color: "green" },
  { name: "BLACK BEANS", category: "Vegetable", color: "green" },
  { name: "CABBAGE", category: "Vegetable", color: "green" },
  { name: "CUCUMBER", category: "Vegetable", color: "green" },
  { name: "FENNEL SEED", category: "Vegetable", color: "green" },
  { name: "KIDNEY BEAN", category: "Vegetable", color: "green" },
  { name: "LIMA BEAN", category: "Vegetable", color: "green" },
  { name: "ONION", category: "Vegetable", color: "green" },
  { name: "RHUBARB", category: "Vegetable", color: "green" },
  { name: "SPINACH", category: "Vegetable", color: "green" },
  { name: "TURNIP", category: "Vegetable", color: "green" },
  { name: "BLACK-EYED PEA", category: "Vegetable", color: "green" },
  { name: "CANNELLINI BEANS", category: "Vegetable", color: "green" },
  { name: "EGGPLANT", category: "Vegetable", color: "green" },
  { name: "JALAPEÑO PEPP", category: "Vegetable", color: "green" },
  { name: "LEAF LETT ", category: "Vegetable", color: "green" },
  { name: "MUSTARD GREENS", category: "Vegetable", color: "green" },
  { name: "PARSNIP", category: "Vegetable", color: "green" },
  { name: "ROMAINE LETT", category: "Vegetable", color: "green" },
  { name: "SWEET POTATO", category: "Vegetable", color: "green" },
  { name: "WAKAME SEAWEED", category: "Vegetable", color: "green" },
  { name: "AVOCADO", category: "Fruit", color: "green" },
  { name: "CHERRY", category: "Fruit", color: "green" },
  { name: "GUAVA", category: "Fruit", color: "green" },
  { name: "LEMON", category: "Fruit", color: "green" },
  { name: "ORANGE", category: "Fruit", color: "green" },
  { name: "PLANTAIN", category: "Fruit", color: "green" },
  { name: "TANGERINE", category: "Fruit", color: "green" },
  { name: "BLACKBERRY", category: "Fruit", color: "green" },
  { name: "FIG", category: "Fruit", color: "green" },
  { name: "HONEYDEW MLN", category: "Fruit", color: "green" },
  { name: "LYCHEE", category: "Fruit", color: "green" },
  { name: "PEACH", category: "Fruit", color: "green" },
  { name: "RED PALM FRUIT", category: "Fruit", color: "green" },
  { name: "BLUEBERRY", category: "Fruit", color: "green" },
  { name: "GRAPE", category: "Fruit", color: "green" },
  { name: "JACKFRUIT", category: "Fruit", color: "green" },
  { name: "MANGO", category: "Fruit", color: "green" },
  { name: "PEAR", category: "Fruit", color: "green" },
  { name: "STAR FRUIT", category: "Fruit", color: "green" },
  { name: "CAPERS", category: "Fruit", color: "green" },
  { name: "GRAPEFRUIT", category: "Fruit", color: "green" },
  { name: "KIWI", category: "Fruit", color: "green" },
  { name: "MULBERRY", category: "Fruit", color: "green" },
  { name: "PERSIMMON", category: "Fruit", color: "green" },
  { name: "STRAWBERRY", category: "Fruit", color: "green" },
  { name: "BEEF", category: "Meat", color: "green" },
  { name: "VEAL", category: "Meat", color: "green" },
  { name: "BISON", category: "Meat", color: "green" },
  { name: "VENISON", category: "Meat", color: "green" },
  { name: "CHICKEN TURKEY", category: "Meat", color: "green" },
  { name: "EGG WHITE", category: "Dairy/Eggs", color: "green" },
  { name: "EGG YOLK", category: "Dairy/Eggs", color: "green" },
  { name: "CATFISH", category: "Seafood", color: "green" },
  { name: "HALIBUT", category: "Seafood", color: "green" },
  { name: "SNAPPER (RED)", category: "Seafood", color: "green" },
  { name: "TUNA", category: "Seafood", color: "green" },
  { name: "CLAM", category: "Seafood", color: "green" },
  { name: "LOBSTER", category: "Seafood", color: "green" },
  { name: "SWORDFISH", category: "Seafood", color: "green" },
  { name: "CODFISH", category: "Seafood", color: "green" },
  { name: "SALMON", category: "Seafood", color: "green" },
  { name: "TILAPIA", category: "Seafood", color: "green" },
  { name: "FLOUNDER", category: "Seafood", color: "green" },
  { name: "SCALLOP", category: "Seafood", color: "green" },
  { name: "TROUT", category: "Seafood", color: "green" },
  { name: "CORN", category: "Grain/Starch", color: "green" },
  { name: "RICE (BRWN/WHT)", category: "Grain/Starch", color: "green" },
  { name: "MILLET", category: "Grain/Starch", color: "green" },
  { name: "TAPIOCA", category: "Grain/Starch", color: "green" },
  { name: "OAT (GLUTEN FREE)", category: "Grain/Starch", color: "green" },
  { name: "TEFF", category: "Grain/Starch", color: "green" },
  { name: "QUINOA", category: "Grain/Starch", color: "green" },
  { name: "ANCHO CHILI PEPP", category: "Herb/Spice", color: "green" },
  { name: "CARDAMOM", category: "Herb/Spice", color: "green" },
  { name: "HORSERADISH", category: "Herb/Spice", color: "green" },
  { name: "PARSLEY", category: "Herb/Spice", color: "green" },
  { name: "BASIL", category: "Herb/Spice", color: "green" },
  { name: "CHIVES", category: "Herb/Spice", color: "green" },
  { name: "LICORICE", category: "Herb/Spice", color: "green" },
  { name: "PEPPERMINT", category: "Herb/Spice", color: "green" },
  { name: "BAY LEAF", category: "Herb/Spice", color: "green" },
  { name: "CINNAMON", category: "Herb/Spice", color: "green" },
  { name: "OREGANO", category: "Herb/Spice", color: "green" },
  { name: "ROSEMARY", category: "Herb/Spice", color: "green" },
  { name: "BLACK PEPPER", category: "Herb/Spice", color: "green" },
  { name: "GINGER", category: "Herb/Spice", color: "green" },
  { name: "PAPRIKA", category: "Herb/Spice", color: "green" },
  { name: "THYME", category: "Herb/Spice", color: "green" },
  { name: "ALMOND", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "CASHEW", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "FLAXSEED", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "HEMP", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "PECAN", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "SESAME", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "BRAZIL NUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "CHAMOMILE", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "GARLIC", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "MACADAMIA", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "PINE NUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "SPEARMINT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "BREWER'S YEAST", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "COCOA", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "GREEN TEA", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "MUSTARD SEED", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "PISTACHIO", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "STEVIA LEAF", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "CANOLA (RAPESEED)", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "COCONUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "HAZELNUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "PEANUT", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "POPPY SEED", category: "Nuts/OilsMiscFood", color: "green" },
  { name: "VANILLA", category: "Nuts/OilsMiscFood", color: "green" },
]
module.exports = { menuStart };